CREATE DATABASE UMAIYAL;
USE UMAIYAL;
DROP DATABASE UMAIYAL;
DROP DATABASE if exists UMAIYAL;

CREATE TABLE STUDENT(
ID INT PRIMARY KEY ,
NAME VARCHAR (30),
TAMIL INT ,
ENGLISH INT,
MATHS INT,
DEPARTMENT varchar(20)
);

describe STUDENT;
ALTER TABLE STUDENT ADD COLUMN AGE INT;
ALTER TABLE STUDENT DROP AGE;

INSERT INTO STUDENT VALUES (1,"SATHISH",45,35,45,"COM"),(2,"KUMAR",45,25,45,"BIO"),(3,"SARITHA",50,35,35,"COM"),(4,"SAI",40,39,41,"MAT"),(5,"ANAND",35,40,41,"COM"),(6,"BOO",40,41,45,"BIO"),(7,"CHINNAA",40,44,38,"MAT"),(8,"THARA",38,39,37,"BIO"),(9,"DURGA",40,44,41,"COM"),(10,"RAM",40,40,40,"COM");
SELECT * FROM STUDENT;
INSERT INTO STUDENT (ID ,NAME,TAMIL) VALUES(11,"LATHAA",50);

SELECT *FROM STUDENTS;
SELECT ID,NAME FROM STUDENT;
SELECT ID,NAME ,TAMIL  FROM STUDENT;
SELECT NAME,TAMIL FROM STUDENT;

-- WHERE COMMEND 

SELECT NAME,TAMIL FROM STUDENT
WHERE TAMIL=40;

SELECT ID,NAME,TAMIL,DEPARTMENT FROM STUDENT
where DEPARTMENT="COM";

SELECT * FROM STUDENT
WHERE TAMIL <40;

SELECT *FROM STUDENT
WHERE NAME ="SATHISH";

SELECT *FROM STUDENT
WHERE NAME <> "SATHISH";

SELECT * FROM STUDENT
WHERE TAMIL>40 AND DEPARTMENT="BIO";

SELECT *FROM STUDENT
WHERE TAMIL<40 OR DEPARTMENT="COM";

SELECT * FROM STUDENT
WHERE DEPARTMENT IN ("MAT","COM");

SELECT *FROM STUDENT
WHERE TAMIL IN(40,35)
LIMIT 3;


SELECT * FROM STUDENT
WHERE NAME LIKE 'S%';

select * FROM STUDENT
WHERE NAME LIKE 'D%A';

SELECT * FROM STUDENT
WHERE NAME LIKE '%I%' ;

SELECT * FROM STUDENT
WHERE TAMIL LIKE '3%8';

UPDATE STUDENT
SET DEPARTMENT="OK"
WHERE DEPARTMENT="COM";

DELETE FROM STUDENT
WHERE ID=11;

SELECT distinct DEPARTMENT
FROM STUDENT;

SELECT * FROM STUDENT
order by NAME;

SELECT * FROM STUDENT
ORDER BY TAMIL;

SELECT * FROM STUDENT
ORDER BY ENGLISH desc;

SELECT * FROM STUDENT
order by (case name
WHEN "DURGA" THEN 1
WHEN "RAM" THEN 2
WHEN "BOO" THEN 3
ELSE 100 END
);