-- fumction
CREATE database SAM;
USE SAM;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY ,
NAME VARCHAR (30),
TAMIL INT ,
ENGLISH INT,
MATHS INT,
DEPARTMENT varchar(20)
);

INSERT INTO STUDENT VALUES (1,"SATHISH",45,35,45,"COM"),(2,"KUMAR",45,25,45,"BIO"),(3,"SARITHA",50,35,35,"COM"),(4,"SAI",40,39,41,"MAT"),(5,"ANAND",35,40,41,"COM"),(6,"BOO",40,41,45,"BIO"),(7,"CHINNAA",40,44,38,"MAT"),(8,"THARA",38,39,37,"BIO"),(9,"DURGA",40,44,41,"COM"),(10,"RAM",40,40,40,"COM");
SELECT * FROM STUDENT;

-- AGGREGATE FUNCTION

SELECT count(*) FROM STUDENT;

SELECT COUNT(*) FROM STUDENT
WHERE DEPARTMENT ="COM";

select avg(TAMIL) AS AVERAGE FROM STUDENT;
SELECT sum(TAMIL) AS SUMOF_TOTAL FROM STUDENT;
SELECT max(TAMIL) AS MAXIMIU FROM STUDENT;

-- STRING

SELECT Lcase(NAME) AS NAME,TAMIL FROM STUDENT;
SELECT NAME , char_length(NAME) CHER_COUNT FROM STUDENT;
SELECT NAME,concat("MARK=",TAMIL) FROM STUDENT;


-- DADE FUNCTION


ALTER TABLE STUDENT ADD COLUMN EX_DATE DATE;
describe STUDENT;
update STUDENT
SET EX_DATE ="2023/05/22";

SELECT NOW();
select DATE(NOW());
SELECT current_date();
SELECT date_format(CURDATE(),"%D-%M-%Y") AS DATE;

SELECT datediff(CURDATE(),"2022/02/11") AS DIFFERENT;
SELECT date_add(curdate(),INTERVAL 10 DAY ) AS "AFTER 10 DAY" ;






