CREATE DATABASE SRIDEVI;
USE SRIDEVI;

CREATE TABLE EMPLOYE (
ID INT PRIMARY KEY,
NAME VARCHAR (20),
JOB_DESCRIP VARCHAR(20),
SALARY INT
);
DROP table EMPLOYE;

INSERT INTO EMPLOYE VALUES(1,"SATHISH","MANAGER",100000),(2,"KUMAR","SALES",200000),(3,"SARITHA","MANAGER",200000),(4,"THARA","TEEMLEADER",100000),(5,"THARAGAI","MANAGER",100000);
describe EMPLOYE;
SELECT * FROM EMPLOYE;

-- GROUB BY

SELECT JOB_DESCRIP,avg(SALARY) FROM EMPLOYE 
group by JOB_DESCRIP;

SELECT JOB_DESCRIP,count(ID) FROM EMPLOYE
group by JOB_DESCRIP;

-- having

SELECT JOB_DESCRIP,count(ID) FROM EMPLOYE
group by JOB_DESCRIP
having count(ID)>1;

SELECT JOB_DESCRIP,avg(SALARY) FROM EMPLOYE 
group by JOB_DESCRIP
having avg(SALARY)>100000; 

-- constraints

-- add not null constrain
ALTER TABLE EMPLOYE
MODIFY NAME varchar(20) NOT NULL;

-- DROP NIT NULL 
ALTER TABLE EMPLOYE
MODIFY NAME varchar(20);

-- ADD DEFAULT TABLE 
 ALTER TABLE EMPLOYE
 ALTER JOB_DESCRIP SET DEFAULT "UNASSIGNE";
 
 -- DROP DEFAULT table
 ALTER  TABLE EMPLOYE
 ALTER JOB_DESCRIP DROP DEFAULT;
 
 -- ADD CHECK CONSTRAINE
 
 ALTER TABLE EMPLOYE 
 ADD CHECK (SALARRY>100000) ;
 
 -- FOREIGN KEY
 
 create TABLE BRANCH(
 BRANCH_ID INT primary KEY auto_increment,
 NAME VARCHAR(20),
 ADDRES VARCHAR(20)
 );
  DROP TABLE BRANCH;

CREATE TABLE EMPLOYE (
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR (20) NOT NULL ,
JOB_DESCRIP VARCHAR(20) default " MANAGER",
SALARY INT default "2",
BRANCH_ID INT ,
constraint DROP_NAME foreign key (BRANCH_ID) references BRANCH (BRANCH_ID)
ON delete SET NULL    
);
 DROP TABLE EMPLOYE;
--  IF YOU WANT TO DROP  BRANCH table YOU CAN'T ,ONLT IF YPU CUT THE LINK BOTH TABLES YOU CAN.
ALTER table EMPLOYE
DROP foreign key DROP_NAME;

DROP TABLE BRANCH;

-- INDEX 

SHOW INDEX FROM EMPLOYE;

CREATE INDEX NAME_INDEX ON  EMPLOYE (NAME);

ALTER table EMPLOYE
DROP INDEX NAME_INDEX;

ALTER TABLE EMPLOYE
ADD INDEX (NAME);

-- ON DELET

INSERT INTO  BRANCH (NAME) VALUES("SATHISH");
INSERT INTO BRANCH(NAME) values ("RAM"),("SARITHA");
SELECT * FROM BRANCH;

INSERT INTO EMPLOYE (NAME,BRANCH_ID) values ("LATHAA",1),("DURGA",2),("POO",3);
SELECT * FROM EMPLOYE;

delete FROM BRANCH
WHERE BRANCH_ID =1;
