CREATE DATABASE POO;
USE POO;

drop database poo;
CREATE TABLE BRANCH(
BRANCH_ID INT primary KEY auto_increment,
B_NAME VARCHAR (20),
ADDR varchar(100)
);

CREATE TABLE DATAS (
 ID INT primary key  ,
 NAME VARCHAR (20),
 JOB varchar(20),
 SALARY INT,
 FOR_ID INT,
 constraint DROB_NAME FOREIGN KEY (FOR_ID) references BRANCH(BRANCH_ID) 
 );
 
 INSERT INTO BRANCH VALUES(1,"CHEANNAI","A1 123"),(2,"SALAME","A2 123"),(3,"NAMAKAL","A3123");
 INSERT INTO DATAS VALUES(1,"SATHISH","IT",100000,1);
 INSERT INTO DATAS VALUES (2,"SARITHA","IT",100000,1);
 INSERT INTO DATAS VALUES (3,"THARAGAI","CSC",200000,2);
 INSERT INTO DATAS VALUES (4,"THARANI","BIO",200000,3);
 INSERT INTO DATAS (ID,NAME,JOB) VALUES (5,"SAI","CSC");
 INSERT INTO DATAS (ID,NAME,JOB) VALUES (6,"RAM","CSC");
SELECT * FROM BRANCH;
SELECT * FROM DATAS;

-- INNER JOIN 

SELECT DATAS.ID,DATAS.NAME,DATAS.JOB,DATAS.FOR_ID,BRANCH.B_NAME FROM DATAS
INNER JOIN BRANCH
ON DATAS.FOR_ID=BRANCH.BRANCH_ID;

--  LEFT JOIN IS DATAS TABLE 

SELECT DATAS.ID,DATAS.NAME,DATAS.JOB,DATAS.FOR_ID,BRANCH.B_NAME FROM DATAS
LEFT JOIN BRANCH
ON DATAS.FOR_ID=BRANCH.BRANCH_ID; 

-- WE  USE WHERE CAN DO LIKE INNER JOIN
 
SELECT DATAS.ID,DATAS.NAME,DATAS.JOB,DATAS.FOR_ID,BRANCH.B_NAME FROM DATAS ,BRANCH
where DATAS.FOR_ID=BRANCH.BRANCH_ID;

-- RIGHT JOIN 

SELECT DATAS.ID,DATAS.NAME,DATAS.JOB,DATAS.FOR_ID,BRANCH.B_NAME FROM DATAS
right JOIN BRANCH
ON DATAS.FOR_ID=BRANCH.BRANCH_ID; 
 
 -- CRASS JOIN
 
SELECT DATAS.ID,DATAS.NAME,DATAS.JOB,DATAS.FOR_ID,BRANCH.B_NAME FROM DATAS
cross JOIN BRANCH;


-- kull join not available in my sql


-- br_name emp_couunt

SELECT BRANCH.B_NAME ,count(DATAS.ID) FROM BRANCH
JOIN DATAS
ON BRANCH.BRANCH_ID = DATAS.FOR_ID
GROUP BY DATAS.FOR_ID;

SELECT BB.B_NAME ,count(DD.ID) AS NOUMBER_OF_COUNT FROM BRANCH AS BB
JOIN DATAS AS DD
ON BB.BRANCH_ID = DD.FOR_ID
GROUP BY DD.FOR_ID;

